# Console System - (c) 2026 zTieuYeuz. All rights reserved.
---
systemd: true
dbus: true
dbus-symlink: true
entropy-copy: true
entropy-files:
    - /var/lib/urandom/random-seed
    - /var/lib/systemd/random-seed
