---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false
requirements:
    # He thong da cai chiem ~4GB; de du cho nhat ky va file tai len.
    requiredStorage:    8
    requiredRam:        1.0
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
